# Generated by Django 3.1.2 on 2020-11-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denkmalgeschutztelofts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Kontakt',
        ),
    ]
