# Generated by Django 3.1.2 on 2020-11-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denkmalgeschutztelofts', '0003_email_kontakt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(default='not given!', max_length=200),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='email',
            field=models.CharField(default='not given!', max_length=200),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='nachname',
            field=models.CharField(default='not given!', max_length=200),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='telefon',
            field=models.CharField(default='not given!', max_length=200),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='vorname',
            field=models.CharField(default='not given!', max_length=200),
        ),
    ]
