# Generated by Django 3.1.2 on 2020-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denkmalgeschutztelofts', '0004_auto_20201116_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='quelle',
            field=models.CharField(choices=[('KT', 'Kontakt'), ('KD', 'Kaiser und Dicke'), ('NS', 'Newsletter'), ('AN', 'Angebot'), ('RB', 'Rubenstrasse')], default='KT', max_length=2),
        ),
    ]
