# Generated by Django 3.1.4 on 2020-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denkmalgeschutztelofts', '0005_auto_20201213_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='quelle',
            field=models.CharField(choices=[('KT', 'Kontakt'), ('KD', 'Kaiser und Dicke'), ('NS', 'Newsletter'), ('AN', 'Angebot'), ('RB', 'Rubenstrasse '), ('RP', 'PDF Rubenstrasse'), ('KP', 'PDF Kaiser und Dicke')], default='KT', max_length=2),
        ),
    ]
