# Generated by Django 3.1.4 on 2021-02-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denkmalgeschutztelofts', '0008_auto_20210103_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='quelle',
            field=models.CharField(choices=[('KT', 'Kontakt'), ('AK', 'Angebot Kaiser und Dicke'), ('AR', 'Angebot Rubenstrasse'), ('AT', 'Angebot Teschemacher Hof'), ('AM', 'Angebot Turmchengebaude'), ('NS', 'Newsletter'), ('AN', 'Angebot'), ('RB', 'Rubenstrasse '), ('KD', 'Kaiser und Dicke'), ('TH', 'Teschemacher Hof'), ('TU', 'Turmchengebaude'), ('IN', 'Home Page')], default='KT', max_length=2),
        ),
    ]
