# Generated by Django 3.1.2 on 2020-11-23 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20201116_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
        ),
    ]
