# Generated by Django 3.1.4 on 2021-01-02 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20201220_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 1, 4)),
        ),
    ]
