# Generated by Django 3.1.4 on 2021-01-12 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20210102_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 1, 18)),
        ),
    ]
