# Generated by Django 3.1.4 on 2021-02-12 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20210112_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 2, 15)),
        ),
    ]
